version: "3.7"
services:
  django:
    build: ./backend
    volumes:
      - ./backend:/app/backend
      - ./docs:/app/docs
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.development
    stdin_open: true
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
  react-ts:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: base
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/home/node/app/src
      # One-way volume to use node_modules from inside image
      - ./frontend/nodemon.json:/home/node/app/nodemon.json
    container_name: title-search
    expose:
      - "4000"
    ports:
      - "4000:4000"

    depends_on:
      - django
    command: npm run dev
